name: Check Code

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "00 01 * * *"

permissions: read-all

jobs:
  build_and_scan_docker_image:
    name: Build and scan docker image
    permissions:
      contents: write
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - "linux/amd64"
          - "linux/arm64/v8"
          - "linux/arm/v7"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - id: dotenv
        uses: falti/dotenv-action@v1.0.4
      - id: platform
        run: |
          echo 'id=${{ matrix.platform }}' | sed 's:/:-:g' >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          load: true
          tags: "${{ steps.dotenv.outputs.name }}:${{ steps.platform.outputs.id }}"
      - run: |
          docker images
      - id: grype
        uses: anchore/scan-action@v3
        with:
          image: "${{ steps.dotenv.outputs.name }}:${{ steps.platform.outputs.id }}"
          fail-build: true
          severity-cutoff: critical
      - name: Upload the vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.grype.outputs.sarif }}
          category: grype
      - uses: aquasecurity/trivy-action@master
        with:
          image_ref: "${{ steps.dotenv.outputs.name }}:${{ steps.platform.outputs.id }}"
          format: "sarif"
          output: "trivy-results.sarif"
      - name: Upload the vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
          category: trivy
